language: node_js

node_js:
  - "8.11.1"

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x64

osx_image: xcode9.0

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - xvfb
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev-dev

script:
  - npm test